%%{init: {'theme':'default', flowchart: {'htmlLabels': false}}}%%

flowchart TB
    %% nodes

    curves[(Stress-stretch curves)]

    subgraph predictor_pre_selection[Predictor pre-selection]
        exp(Exponential)
        pca(PCA)
        logistic(Logistic)
        best_fit{Best fit}
    end


    images[(Images)]

    subgraph hparam_search[Hyperparameter search]
        study1["Successive halving Search 1"]
        study2["Hyperband search 2"]
        study3["Hyperband search 3"]
        best_config{Best configuration}
    end

    subgraph training["Model training (on top k images)"]
        train5[Model 5]
        train10[Model 10]
        train15[Model 15]
        train20[Model 20]
        trainall[Model all]
        best_val{Best validation}
    end

    subgraph testing[Testing]
        ensemble[Snapshot ensembling]
        test[Test model]
    end

    subgraph xai[XAI]
        ig[Integrated gradients]
        occ[Occlusion]
        why{Why?}
    end

    %% Connections

    curves --> predictor_pre_selection
    exp & pca & logistic --> best_fit
    best_fit --> hparam_search
    images ----> hparam_search
    study1 & study2 & study3 --> best_config
    best_config --> training
    train5 & train10 & train15 & train20 & trainall --> best_val
    best_val --> testing
    ensemble --> test
    test --> xai
    ig & occ --> why